name: lint, test and RUN
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make install
      - run: make db-setup
      - run: make lint
      - run: make test
      - run: make run